Proposal to improve scheduling
ironcore-dev/ironcore pull request #1128
Opened 2024-09-30 08:48 UTC by lukasfrank

# Proposed Changes

- This proposal discusses possible solution to improve IronCore scheduling

2024-09-30 11:19 UTC, balpert89 commented
+1 for the proposal. This addresses a lot of current pain points in the stack:

- better utilization for dedicated machine pools
- a transparent decision making process how a `Machine` resource ended up on a given `MachinePool`
- adding custom resources for scheduling decisions such as `EPC Memory`

Going into more detail. The current proposed approach follows a decentralized solution whereas the centralized one (in the alternatives section) follows the network stack solution. There are some disadvantages with a clustered solution, such as lack of guaranteed availability. For networking this is okay because if a critical infrastructure component is down, networking is affected anyway. The scheduling part should not have such a big impact for computing - using the decentralized approach would isolate impact on a pool level. 
Another aspect with a centralized solution is you have to deal with a lot of "boilerplate" challenges such as "eventual consistency", giving room for possible race conditions. The `Reservations` solution solves this pretty elegantly because you can introduce a time peroid until a scheduler waits for its decision and only takes the pools into consideration it finds in the status slice. Therefore, my vote goes with a decentralized approach here.

On the topic of the "scheduling decision". The reservation system is meant to have a decision *who* can provide the requested resources. Another controller can then use this to actually decide which one of those pools to actually use for the the `Machine` resource. This enables a similar behavior compared with `Node` <-> `Pod` scheduling in vanilla Kubernetes. Another point to consider is that you can enable "system" reservations to accomodate for resources that are exclusively reserved for system applications.

Some aspects that are unclear for me:
- who decides the `rating` on a given status entry, is this similar to a `priority`? How does this influence the scheduling decision?
- how will arbitrary resources be announced, such as the already mentioned `EPC Memory`? Or e.g. dedicated graphics cards?

2024-09-30 11:36 UTC, lukasfrank commented
> * who decides the `rating` on a given status entry, is this similar to a `priority`? How does this influence the scheduling decision?

Only the `pool provider` can calculates the rating (since it's the component to check if the reservation can be fulfilled)  and it is a metric on "how good the `Reservation` fits onto the related pool". It should be understood as a hint for the scheduler to take the decision. 

> * how will arbitrary resources be announced, such as the already mentioned `EPC Memory`? Or e.g. dedicated graphics cards?

In the distributed approach: There is no need anymore for announcing resources. The resource "owner" (the `pool provider`) is in charge of taking or rejecting the reservation and needs to keep track of all the resources. If arbitrary resources aren't available on a specific host, the reservation will be declined.

2024-09-30 12:07 UTC, balpert89 commented
The `rating` part is clear for me now, thanks for addressing.

> In the distributed approach: There is no need anymore for announcing resources. The resource "owner" (the pool provider) is in charge of taking or rejecting the reservation and needs to keep track of all the resources. If arbitrary resources aren't available on a specific host, the reservation will be declined.

Does that mean we will deprecate the `allocatable` / `available` (https://github.com/ironcore-dev/ironcore/blob/main/api/compute/v1alpha1/machinepool_types.go#L30-L33) fields as they are not required anymore?

2024-09-30 13:14 UTC, lukasfrank commented
> The `rating` part is clear for me now, thanks for addressing.
> 
> > In the distributed approach: There is no need anymore for announcing resources. The resource "owner" (the pool provider) is in charge of taking or rejecting the reservation and needs to keep track of all the resources. If arbitrary resources aren't available on a specific host, the reservation will be declined.
> 
> Does that mean we will deprecate the `allocatable` / `available` (https://github.com/ironcore-dev/ironcore/blob/main/api/compute/v1alpha1/machinepool_types.go#L30-L33) fields as they are not required anymore?

Correct, there would be no need for this fields anymore. In case if it's used to aggregate the resources of the entire infrastructure, we can offer metrics and aggregate it the kubernetes way.

2025-04-09 08:38 UTC, afritzler commented
Can we maybe rename the proposal and the PR. Multi-level scheduling seems to be to generic.

2025-04-10 14:36 UTC, afritzler requested changes

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +oep-number: 11
Please change oer to iep here and in all existing proposals.

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +Scheduling resources is a central process to increase utilization of cloud infrastructure. It not only involves the process to find any feasible `pool` but rather, if possible, to find an optimal com
Instead of refering to a general `pool` I would pin this down to `MachinePools` only.

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +Scheduling resources is a central process to increase utilization of cloud infrastructure. It not only involves the process to find any feasible `pool` but rather, if possible, to find an optimal com
Also, what does "optimal" mean in this context? Should we rather say here that we find a `MachinePool` which can fullfil the resource request of a `Machine` and is able to materialize a `Machine`.

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +With `ironcore` a multi-level hierarchy can be built to design availability/failure zones. `Machine`s can be created on every layer, which are subsequently scheduled on the compute `Node`s  in the hi
Instead of compute `Node` I would refer here to compute `Pools` or `MachinePools`.

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +With `ironcore` a multi-level hierarchy can be built to design availability/failure zones. `Machine`s can be created on every layer, which are subsequently scheduled on the compute `Node`s  in the hi
Also what are the current limitations of the implementation. We should list them here and point out that this proposal wants to address those.

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +- The scheduler should not act on `Machine` updates like `NetworkInterface` attachments
This proposal does not cover the scheduling of `Volumes`.

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +For every created `Machine` a resource `Reservation` object will be created. The `poollet` will continue to broker only `Machine`s with a `.spec.machinePoolRef` set. The `Reservation` is a condensed
Instead of "after some time" I would rather state that as soon as a root (origin) `Reservation` as an available `MachinePool` in it's status, this pool will be picked by the scheduler for assigning the `.spec.machinePoolRef` of a `Machine`.

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +For every created `Machine` a resource `Reservation` object will be created. The `poollet` will continue to broker only `Machine`s with a `.spec.machinePoolRef` set. The `Reservation` is a condensed
Instead of focusing on the brokering aspect I would rather write that the `machinepoollet` will call the `CreateMachine` IRI interface method to create the `Machine` against the IRI interface implementor. This can result either in a brokering of a `Machine` object from one cluster to another or the creation of a VM in case the IRI implementor is e.g. the `libvirt-provider` or any other concrete compute provider implementation.

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +      state: rejecting
Can we come up here with better states than: accepting/rejecting?

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +1. If `.spec.machinePoolRef` is not set, the scheduler creates a `Reservation` that includes the required resources.
Creates a `Reservation` for all available pools in the particular cluster.

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +3. `poriver` evaluates the `Reservation` and sets its state to `accepting` or `rejecting`, which is then propagated up the hierarchy.
Typo `provider`.

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +6. Scheduler will delete top `Reservation` which triggers deletion of all brokered `Reservation`s
When does it delete the root (origin) `Reservation`?

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +- `Reservation`s can also be used to block resources for a specific use-case
Without creating a `Machine` object?

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +- One more resource (`Reservations`) is being introduced
Increases complexity in the scheduling by introducing a new resource (`Reservation`) and the scheduler flow has to be extended.

2025-04-10 14:36 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +- If central cluster is not reachable, no `Machine` can be placed
No easy way to dynamicallt change pool hirarchy.

2025-04-10 15:55 UTC, balpert89 commented on docs/proposals/11-scheduling.md
> +- `Reservation`s can also be used to block resources for a specific use-case
i would imagine this can be used for system components other than `Machine`s. Though I am not sure if other sub-systems would be a better fit to leverage this.

2025-04-11 07:20 UTC, afritzler requested changes

2025-04-11 07:20 UTC, afritzler commented on docs/proposals/11-scheduling.md
> +limitations of the current implementation:
No. 1 is a limitation No. 2 is an implementation detail which we have. The biggest limitation however is that we can not guarantee at the moment that we find enough resources on a compute pool and blindly schedule `Machine` objects onto pools even though they might not be fullfilled.

2025-04-11 08:04 UTC, lukasfrank commented on docs/proposals/11-scheduling.md
> +limitations of the current implementation:
> No. 2 is an implementation detail which we have 
which is a limitation since we at the moment only support CPU and memory

2025-04-11 10:01 UTC, balpert89 commented on docs/proposals/11-scheduling.md
> +2. the corresponding `Machine` is being placed on the pool provider.
the order of those points should be switched because the `machine` is essentially replacing the `reservation`.

2025-04-11 10:04 UTC, balpert89 commented on docs/proposals/11-scheduling.md
> +The status of the `Reservation` is being propagated up to the layer where it was created. As soon as the root
how is it ensured that a scheduler on a lower hierarchy level does not start scheduling / acting upon the update for the particular `reservation` object? the status is consecutively brokered up so an intermediate layer will see an update to the `reservation` before the "root" `reservation` / scheduler.

2025-04-11 10:05 UTC, balpert89 commented on docs/proposals/11-scheduling.md
> +The status of the `Reservation` is being propagated up to the layer where it was created. As soon as the root
ah forget this, as soon as i hit "add" i realized there is no `machine` object on that intermediate layer because brokering for the `machine` only starts when it has a machinepool reference set.

2025-04-11 10:07 UTC, balpert89 commented on docs/proposals/11-scheduling.md
> +2. `poollet`s which match `.spec.pools` of `Reservation` pick it up and broker it one layer down
when `.spec.pools` is left empty all pools are considered?

2025-04-11 10:09 UTC, balpert89 commented on docs/proposals/11-scheduling.md
> +   `Bound` state.
should we describe the possible states for a `reservation` and also for the decision of a provider in `.status.pools[].state`?

2025-04-11 10:11 UTC, balpert89 commented on docs/proposals/11-scheduling.md
> +- No easy way to dynamicallt change pool hirarchy.
typos

2025-04-11 10:13 UTC, balpert89 commented on docs/proposals/11-scheduling.md
> +### Disadvantages
another point here is that to model this correctly a poollet has to be aware of if its a leave or a branch poollet. This is required here to correctly model the topology as a branch poollet needs to announce the grouped machinepools under its own aggregated pool.

2025-04-11 11:37 UTC, lukasfrank commented on docs/proposals/11-scheduling.md
> +### Disadvantages
I think it's covered with this point, right? `- Layered structure of hierarchy needs to be duplicated at central place`

2025-04-11 13:09 UTC, balpert89 commented on docs/proposals/11-scheduling.md
> +### Disadvantages
the importance is that it requires a change in the poollet / broker design that could potentially break the current approach for those components.

2025-04-11 14:41 UTC, lukasfrank commented on docs/proposals/11-scheduling.md
> +      rating: 2
As discussed offline: We will keep this out for now since the aggregation of the `rating` is not defined until now. Furthermore we might can solve this issue with a SGX-`MachineClass`. But let's revisit the topic of "optimal" scheduling once we gained some experience with the new approach.

2025-04-24 09:17 UTC, afritzler reviewed
The propsal looks good from my side. As we are only covering the `MachineRuntimeInterface` maybe we should reflect that in the title of the proposal.

2025-04-24 11:29 UTC, afritzler approved these changes

2025-04-24 11:30 UTC, merged