Add e2e example for `Machine` creation using non ephemeral resources
ironcore-dev/ironcore pull request #1136
Opened 2024-10-22 04:59 UTC by Rohit-0505

# Proposed Changes

- Add e2e example manifests for `machine` creation using ephemeral `volume` and `networkinterface`

Fixes #1129 (partially)

2024-10-28 08:37 UTC, afritzler requested changes
Can we name the sample folder `machine-with-ephemeral` resources? This naming scheme would fit better to the existing e2e examples.

2024-10-28 10:58 UTC, Rohit-0505 commented
> Can we name the sample folder `machine-with-ephemeral` resources? This naming scheme would fit better to the existing e2e examples.

done

2024-11-04 07:59 UTC, afritzler requested changes

2024-11-04 07:59 UTC, afritzler commented on config/samples/e2e/bases/machine-with-ephemeral-resources/machine.yaml
> +  - name: root-disk-1
Can we name this volume `root-disk`.

2024-11-04 07:59 UTC, afritzler commented on config/samples/e2e/machine-with-ephemeral-resources/README.md
> +  - name: root-disk-1
`root-disk`

2024-11-11 08:59 UTC, afritzler approved these changes

2024-11-11 09:00 UTC, merged