Migrate proto generation to `buf`
ironcore-dev/ironcore pull request #1139
Opened 2024-10-25 11:56 UTC by afritzler

# Proposed Changes

- Migrate proto generation to `buf`
- Update linter configuration
- Fix linting issues

Fixes #1138

2024-11-05 06:09 UTC, balpert89 commented on .golangci.yml
> +  disable-all: true
I agree with @lukasfrank, other projects (looked at [prometheus](https://github.com/prometheus/prometheus/blob/main/.golangci.yml#L7) and some [grafana projects](https://github.com/grafana/loki/blob/main/.golangci.yml#L53)) use the same pattern to only disable unwanted linters. Golang CI Lint also adds linters with new updates which would be removed, as such you have the overhead to also review those changes as they come in. With an inverse you will eventually see failed golangcilint runs and can decide if this a valid issue or if the linter (or its check) should be disabled.

As per [golangcilint documentation](https://golangci-lint.run/usage/configuration/#linters-configuration) both `enable-all` and `disable-all` fields are `false` by default to achieve both patterns :)

2024-11-12 13:13 UTC, lukasfrank requested changes

2024-11-12 13:13 UTC, lukasfrank commented on buf.gen.yaml
> +  - remote: buf.build/protocolbuffers/go
It seems like we are calling an external API by using a `remote` plugin. 
We might want to get rid of it.

```
➜  ironcore git:(enh/proto-generation) ✗ buf generate
Failure: too many requests

Please see https://buf.build/docs/bsr/rate-limits for details about BSR rate limiting.
```

2025-04-07 08:04 UTC, lukasfrank approved these changes

2025-04-07 10:49 UTC, merged