feat: implement a split client for brokers
ironcore-dev/ironcore pull request #1165
Opened 2024-11-19 11:06 UTC by balpert89

# Proposed Changes

- Pass context (`ctx`) to server creation functions for better resource management.
- Implement an in-memory cache with namespace-specific watching for improved performance.
- Reorganize imports for readability.

Fixes #1156

2024-12-03 10:48 UTC, lukasfrank commented on broker/bucketbroker/server/server.go
> +		DefaultNamespaces: map[string]cache.Config{
Is this needed?

2024-12-04 08:30 UTC, lukasfrank approved these changes

2024-12-04 10:42 UTC, balpert89 commented
rebased.

2024-12-04 10:48 UTC, balpert89 commented
> @balpert89 can you please rebase the PR branch?

done.

2024-12-16 14:25 UTC, afritzler requested changes

2025-04-01 14:10 UTC, merged