Hide resource visibility if user is not in defined group
ironcore-dev/ironcore pull request #856
Opened 2023-09-13 12:14 UTC by lukasfrank

# Proposed Changes

- Added `groups-pool-resources` flag to api-server to define groups which can unhide the pool resources
- If `groups-pool-resources` is empty every user can see pool resources

Fixes #813

2023-09-18 11:44 UTC, afritzler requested changes

2023-09-18 11:44 UTC, afritzler commented on internal/rbac/rbac.go
> +	println(strings.Join(user.GetGroups(), ", "), "vs", strings.Join(groups, ", "))
Do we want to really use `println` here?

2023-09-18 11:44 UTC, afritzler commented on internal/app/apiserver/apiserver.go
> +	fs.StringSliceVar(&o.GroupsToShowPoolResources, "groups-pool-resources", o.GroupsToShowPoolResources,
How about naming the flag `--pool-status-view-allowed-groups`?

2023-09-18 11:44 UTC, afritzler commented on internal/app/compute_test.go
> +			Expect(machinePools.Items[0].Status.Allocatable).To(BeNil())
How about using `ContainElement` and `HaveFields` for those array checks.

2023-09-18 11:44 UTC, afritzler commented on internal/app/storage_test.go
> +			Expect(volumePools.Items[0].Status.Allocatable).To(BeNil())
Same as above.

2023-09-22 06:27 UTC, adracus commented
Can we have this concept in a more extensible way?
* Currently, via this flag, all pools are affected - fine grained control is not possible / extending this to other resources requires lots of coding and flag-passing again
* The white-out happens after the fields are deserialized - can't we somehow enhance the individual codecs to respect custom tags in the struct definition to avoid iterating over the result objects again?

2023-10-04 12:27 UTC, afritzler commented
@adracus how about using a `SubResource` for the pool capacity information? That way we can restrict the access via k8s RBAC and don't have to fiddle around in the `Status` on a per field level who is allowed to see what.

2024-05-31 14:15 UTC, closed without merging